name: bonsoir
description: A Zeroconf library that allows you to discover network services and to broadcast your own. Based on Apple Bonjour and Android NSD.
version: 1.0.1+2 # Remember to also change the version in "ios/bonsoir.podspec", "macos/bonsoir.podspec", and "android/build.gradle".
homepage: https://github.com/Skyost/Bonsoir

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ^1.1.0
  dart_ipify: ^1.1.1
  

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.bonsoir
        pluginClass: BonsoirPlugin
      ios:
        pluginClass: BonsoirPlugin
      macos:	
        pluginClass: BonsoirPlugin
